In [1]:
import numpy as np

# Matrix representation of the given state
Psi = np.array([[1/np.sqrt(6), 1/np.sqrt(3)],
                [0, 1/np.sqrt(2)]])

# Perform SVD
U, S, V_dagger = np.linalg.svd(Psi)

# Print results
print("U matrix:")
print(U)
print("\nSingular values:")
print(S)
print("\nV_dagger matrix:")
print(V_dagger)

# Recover the state using Schmidt decomposition
state_reconstructed = sum([S[i] * np.outer(U[:, i], V_dagger[i, :]) for i in range(len(S))])
print("\nReconstructed state:")
print(state_reconstructed)


U matrix:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Singular values:
[0.95302061 0.30290545]

V_dagger matrix:
[[ 0.30290545  0.95302061]
 [-0.95302061  0.30290545]]

Reconstructed state:
[[ 4.08248290e-01  5.77350269e-01]
 [-5.55111512e-17  7.07106781e-01]]
